from enum import Enum
from typing import Literal

PriceFeedType = Literal[
    "NONE",
    "WETH",
    "PRIMITIVE_CHAINLINK",
    "PRIMITIVE_CHAINLINK_LIKE_ETHX",
    "PRIMITIVE_CHAINLINK_LIKE_WSTETH",
    "PRIMITIVE_CHAINLINK_LIKE_YNETH",
    "PRIMITIVE_REDSTONE",
    "PRIMITIVE_REDSTONE_QUOTED",
    "PRIMITIVE_NON_STANDARD_PRECISION",
    "PRIMITIVE_PENDLE_V2",
    "DERIVATIVE_ARRAKIS_V2",
    "DERIVATIVE_BALANCER_V2_GAUGE_TOKEN",
    "DERIVATIVE_BALANCER_V2_STABLE_POOL",
    "DERIVATIVE_BALANCER_V2_WEIGHTED_POOL",
    "DERIVATIVE_COMPOUND",
    "DERIVATIVE_CURVE",
    "DERIVATIVE_ERC4626",
    "DERIVATIVE_ETHERFI",
    "DERIVATIVE_PEGGED_DERIVATIVES",
    "DERIVATIVE_REVERTING",
    "DERIVATIVE_STADER_SD",
    "DERIVATIVE_UNISWAP_V2_POOL",
    "DERIVATIVE_WSTETH",
    "DERIVATIVE_YEARN_VAULT_V2",
]


PRIMITIVE_PRICE_FEEDS = [
    "PRIMITIVE_CHAINLINK",
    "PRIMITIVE_CHAINLINK_LIKE_ETHX",
    "PRIMITIVE_CHAINLINK_LIKE_WSTETH",
    "PRIMITIVE_CHAINLINK_LIKE_YNETH",
    "PRIMITIVE_REDSTONE",
    "PRIMITIVE_REDSTONE_QUOTED",
    "PRIMITIVE_NON_STANDARD_PRECISION",
    "PRIMITIVE_PENDLE_V2",
]


DERIVATIVE_PRICE_FEEDS = [
    "DERIVATIVE_ARRAKIS_V2",
    "DERIVATIVE_BALANCER_V2_GAUGE_TOKEN",
    "DERIVATIVE_BALANCER_V2_STABLE_POOL",
    "DERIVATIVE_BALANCER_V2_WEIGHTED_POOL",
    "DERIVATIVE_COMPOUND",
    "DERIVATIVE_CURVE",
    "DERIVATIVE_ERC4626",
    "DERIVATIVE_ETHERFI",
    "DERIVATIVE_PEGGED_DERIVATIVES",
    "DERIVATIVE_STADER_SD",
    "DERIVATIVE_UNISWAP_V2_POOL",
    "DERIVATIVE_WSTETH",
    "DERIVATIVE_YEARN_VAULT_V2",
]


class RateAsset(Enum):
    ETH = 0
    USD = 1
